version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ovor
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ovor
    depends_on:
      - db
    ports:
      - '4000:4000'
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - '3000:3000'
volumes:
  db-data:
